### ISSUE TITLE
Feature: Give the user the option to name the .replay file

### ISSUE THREAD

**Issue by jyoo980** [jyoo980/MultilingualProvenanceDebugger#5]
Currently, we choose a random number between 0 and 9 to make sure our `.replay` files are unique. We should give users the option to name this file whatever they want

**Requirements**
* The user should be met with a CL dialogue that asks them to name the `.replay` file
```sh
> sr or q
> Enter a name for this debugging trace (.replay): 
> <name>
> Your trace has been saved in your current working directory as <name>.replay
```

**Comment by alison-li** [comment]
I think I'll be working on this one tonight!

**Comment by jyoo980** [comment]
pls @ me

**Comment by alison-li** [comment]
@jyoo980 I will be working on it

**Comment by jyoo980** [comment]
No that's not what I meant LMAO

Can you let me know when you're working on this? I think we meant to pair on it
